### ISSUE TITLE
Caching features for LTR?

### ISSUE THREAD

**Issue by cmacdonald** [seanmacavaney/pyterrier-caching#17]
Any way that I can cache features for LTR?

Would I need to make a version of scorer cache that caches a np array?

**Comment by seanmacavaney** [comment]
I think ScorerCache can _nearly_ do what you need!

If you set `value="features"` when constructing, it will save that field instead. The only trouble is it has problems loading/saving an np.array. Perhaps we could add an option to pickle values?

**Comment by seanmacavaney** [comment]
closed by #18
